application: windy-semiotics-609
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /\.well-known/acme-challenge/(.+)$
  static_files: _acme_challenge/\1
  upload: _acme_challenge/.+$
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
